id: P1E93F3ED
initial_creation_type: input
source_metadata:
  Title: Suvarṇaprabhāsasūtram
  Editor: Bagchi, S.
  Publisher: The Mithila Institute of Post-Graduate Studies and Research in Sanskrit
    Learning
  Place of Publication: Darbhanga
  Year: '1967'
  Nidānaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tathāgatāyuḥpramāṇanirdeśaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Svapnaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Deśanāparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Kamalākarasarvatathāgatastavaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Śūnyatāparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturmahārājaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Sarasvatīdevīparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Śrīmahādevīparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Sarvabuddhabodhisattvanāmasaṃdhāraṇiparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dṛḍhāpṛthivīdevatāparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Saṃjñeyamahāyakṣasenāpatiparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Devendrasamayarājaśāstraparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Susaṃbhavaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Yakṣāśrayarakṣāparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Daśadevaputrasahasravyākaraṇaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Vyādhipraśamanaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Jalavāhanasya matsyavaineyaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Vyāghrīparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Sarvatathāgatastavaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Nigamanaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:08:35.929828'
last_modified_at: '2022-03-08T16:08:35.929839'
